# name = input("enter your name")
# height = float(input("enter your height"))
# height_in_inches = "{:.2f}".format(height/2.54)
# print(name)
# print("Your height is "+str(height)+'cm')
# print("Your height is "+height_in_inches+'inches')

name = input("Enter your name: ")
email = input("Enter your email: ")
phone = input("Enter your phone: ")
print("UserName: "+name)
print("Email: ", email)
print("Ph: ", phone)
